<?php

/**
 * @file
 * NemID Integration main module file.
 */

/**
 * Implements hook_menu().
 */
function nemid_menu() {
  $items = array();

  $items['admin/config/nemid'] = array(
    'title' => 'NemID Settings',
    'position' => 'right',
    'weight' => -15,
    'access arguments' => array('administer site configuration'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Updating fields with the values from nemlogin request.
 *
 * Works also with the nested structure.
 *
 * @param array $tree
 *   Tree of webform elements.
 * @param array $message
 *   Array with messages.
 */
function nemid_populate_fields_recursive(array &$tree, array $message) {
  foreach (array_keys($tree) as $item_key) {
    $type = NULL;

    if (isset($tree['#tree'])) {
      $type = $tree[$item_key]['#webform_component']['type'];
      $item = & $tree[$item_key];
    }
    else {
      if (isset($tree[$item_key]['type'])) {
        $type = $tree[$item_key]['type'];
      }
      $item = & $tree;
    }

    switch ($type) {
      case 'nemid_cpr':
        if (isset($message['cpr'])) {
          $item['#value'] = $message['cpr'];
          if ($message['cpr'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_pid':
        if (isset($message['pid'])) {
          $item['#value'] = $message['pid'];
          if ($message['pid'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_address':
        if (isset($message['road'])) {
          $address_text = $message['road'] . ' ' . $message['road_no'] . ' ' . $message['floor'] . ' ' . $message['door'];
          $item['#value'] = $address_text;
          if ($message['road'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_coaddress':
        if (isset($message['coname'])) {
          $item['#value'] = $message['coname'];
          if ($message['coname'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_name':
        if (isset($message['name'])) {
          $item['#value'] = $message['name'];
          if ($message['name'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_city':
        if (isset($message['zipcode'])) {
          $item['#value'] = $message['zipcode'] . ' ' . $message['city'];
          if ($message['zipcode'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_com_cvr':
        if (isset($message['cvr'])) {
          $item['#value'] = $message['cvr'];
          if ($message['cvr'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_com_rid':
        if (isset($message['rid'])) {
          $item['#value'] = $message['rid'];
          if ($message['rid'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_com_name':
        if (isset($message['company_name'])) {
          $item['#value'] = $message['company_name'];
          if ($message['company_name'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_com_addr':
        if (isset($message['company_street'])) {
          $item['#value'] = $message['company_street'] . ' ' . $message['company_house_nr'] . ' ' . $message['company_floor'];
          if ($message['company_street'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;

      case 'nemid_com_city':
        if (isset($message['company_zipcode'])) {
          $item['#value'] = $message['company_zipcode'] . ' ' . $message['company_city'];
          if ($message['company_zipcode'] != '') {
            $item['#attributes']['readonly'] = 'readonly';
          }
        }
        break;
    }

    unset($item);
  }

  foreach (array_keys($tree) as $item_key) {
    if (isset($tree[$item_key]['#webform_component'])) {
      if (!empty($tree[$item_key]['#webform_component']['children'])) {
        foreach ($tree[$item_key]['#webform_component']['children'] as $child) {
          nemid_populate_fields_recursive($tree[$item_key][$child['form_key']], $message);
        }
      }
    }
  }
}
